name: whatsapp_sender_flutter
description: WhatsApp Sender Flutter is an unofficial API for Flutter to send bulk messages in Whatsapp
version: 0.2.1
homepage: https://github.com/patricknicolosi/whatsapp_sender_flutter

environment:
  sdk: ">=2.18.2  <3.0.0"

dependencies:
  puppeteer: ^2.17.0
  mime_type: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
